export const FLAT_DATA_REQUEST = "FLAT_DATA_REQUEST"
export const FLAT_DATA_SUCCESS = "FLAT_DATA_SUCCESS"
export const FLAT_DATA_FAILURE = "FLAT_DATA_FAILURE"

export const SINGLE_FLAT_DATA_REQUEST = "SINGLE_FLAT_DATA_REQUEST"
export const SINGLE_FLAT_DATA_SUCCESS = "SINGLE_FLAT_DATA_SUCCESS"
export const SINGLE_FLAT_DATA_FAILURE = "SINGLE_FLAT_DATA_FAILURE"

export const ADD_FLAT_DETAILS_REQUEST = "ADD_FLAT_DETAILS_REQUEST"
export const ADD_FLAT_DETAILS_SUCCESS = "ADD_FLAT_DETAILS_SUCCESS"
export const ADD_FLAT_DETAILS_FAILURE = "ADD_FLAT_DETAILS_FAILURE"

export const UPDATE_FLAT_DETAILS_REQUEST = "UPDATE_FLAT_DETAILS_REQUEST"
export const UPDATE_FLAT_DETAILS_SUCCESS = "UPDATE_FLAT_DETAILS_SUCCESS"
export const UPDATE_FLAT_DETAILS_FAILURE = "UPDATE_FLAT_DETAILS_FAILURE"

export const DELETE_FLAT_REQUEST = "DELETE_FLAT_REQUEST"
export const DELETE_FLAT_SUCCESS = "DELETE_FLAT_SUCCESS"
export const DELETE_FLAT_FAILURE = "DELETE_FLAT_FAILURE"

export const ADD_FLAT_RESIDENT_REQUEST = "ADD_FLAT_RESIDENT_REQUEST"
export const  ADD_FLAT_RESIDENT_SUCCESS = "ADD_FLAT_RESIDENT_SUCCESS"
export const  ADD_FLAT_RESIDENT_FAILURE = "ADD_FLAT_RESIDENT_FAILURE"

export const UPDATE_FLAT_RESIDENT_DETAILS_REQUEST = "UPDATE_FLAT_RESIDENT_DETAILS_REQUEST"
export const UPDATE_FLAT_RESIDENT_DETAILS_SUCCESS = "UPDATE_FLAT_RESIDENT_DETAILS_SUCCESS"
export const UPDATE_FLAT_RESIDENT_DETAILS_FAILURE = "UPDATE_FLAT_RESIDENT_DETAILS_FAILURE"

export const DELETE_FLAT_RESIDENT_REQUEST = "DELETE_FLAT_RESIDENT_REQUEST"
export const DELETE_FLAT_RESIDENT_SUCCESS = "DELETE_FLAT_RESIDENT_SUCCESS"
export const DELETE_FLAT_RESIDENT_FAILURE = "DELETE_FLAT_RESIDENT_FAILURE"

export const REMOVE_ERROR = "REMOVE_ERROR";